# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be5e804a4b6d9a7c329385c11b7a8ec99cbdc2835cfb1826106d43f32c5789572991f9c65d349d374f23cf472451cea2fd075739b353034c72ffb710006d961a

test:
  secret_key_base: 6e14ed7d9d72341054cc3b58e85cd9b0b32b2e61427a185d4b7c81f28befadcc1d1e3a939b725360360f9a758b157a9f13bd7c364cc1e944a4104a13ddcac5ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
